# Generated by Django 5.2.4 on 2025-07-23 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='requirement',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='requirements/'),
        ),
        migrations.AlterField(
            model_name='requirement',
            name='steps_done',
            field=models.JSONField(blank=True, help_text='Checklist of steps done', null=True),
        ),
        migrations.AlterField(
            model_name='requirement',
            name='steps_not_done',
            field=models.JSONField(blank=True, help_text='Checklist of steps not done', null=True),
        ),
    ]
